### ISSUE TITLE
FR - complex paths

### ISSUE THREAD

**Issue by geslotencirkel** [MAKIO135/aioi#1]
A current BitWig OSC script uses complex paths to trigger commands in the API and midi message generation. Would be cool to implement complex paths at some point

**Comment by MAKIO135** [comment]
i need to see which character can be uses as a separator. Or maybe use another pattern in message to address a specific host & path in Λioi:  
`;#0;2f` could send `.2` to the first host:path defined in Λioi  
This could keep ORCΛ's messages short, what do you think about this?

**Comment by geslotencirkel** [comment]
there are some characters available but needs to be decided on with ORCΛ devs. Personal approach is to use paths instead of hosts but thats only since I work with a single audio app to generate sounds and communicate with ORCΛ

**Comment by MAKIO135** [comment]
> there are some characters available but needs to be decided on with ORCΛ devs.  

Yes, Λioi can only use ORCΛ's characters, therefore the use of `;` and `#` as separator in UDP messages.

> Personal approach is to use paths instead of hosts but thats only since I work with a single audio app to generate sounds and communicate with ORCΛ  

Not sure if I was clear, I meant, if you define manually a first host `127.0.0.1:3000 /complex/path` in Λioi, its index could be used directly instead of writing the path in  ORCΛ

**Comment by geslotencirkel** [comment]
oh what. totally missed that. gonna try it !

**Comment by MAKIO135** [comment]
This is not implemented yet, that's what I was suggesting. I'll try to add this soon.

**Comment by MAKIO135** [comment]
This is now implemented in the new release: https://github.com/MAKIO135/aioi/releases/tag/v0.3.5
