### ISSUE TITLE
'assigning' a complex path should be clearer in documentation

### ISSUE THREAD

**Issue by retiredaccountretiredaccountretired** [MAKIO135/aioi#6]
took me like 6 hours of fucking around to realize that to make complex paths you have to hit 'enter' on it before you can get it to save it.
![image](https://user-images.githubusercontent.com/11774547/71457519-297c4400-2753-11ea-85f9-ddb4d3fad1ab.png)

**Comment by MAKIO135** [comment]
yeah definitely! thanks  for the feedback.
Adding that to the documentation right now!
