### ISSUE TITLE
Can't make a new connection

### ISSUE THREAD

**Issue by PlaidDroid** [MAKIO135/aioi#7]
![aioi-bug](https://user-images.githubusercontent.com/26256974/86628252-42f62680-bfe7-11ea-8ca4-bb60ea476c98.gif)

With all the connections removed, there was no way of making a new one!
OS: Ubuntu 20.04

This was the message that got printed when I clicked a lot:
`[22249:0707/002742.995413:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`

**Comment by PlaidDroid** [comment]
**[ Temporary Fix: ]**
- Delete the `aioi` folder in `~/.config`
- Start the application again

**Comment by hugosaintemarie** [comment]
Thank you @PlaidDroid for this bug report 🙂 

@MAKIO135 putting you on track, there's the following error at `/desktop/js/ui.js:248`:

```
Uncaught TypeError: Cannot read property 'ip' of undefined
```

`lastHost` is undefined here, so `addHostLi()` can't be run:

```js
const lastHost = app.config.hosts[app.config.hosts.length - 1];
const newHost = {
    ip: lastHost.ip,
    port: lastHost.port + 1,
    type: lastHost.type,
    oscString: '',
    udpString: ''
 };

addHostLi(newHost);
```

**Comment by PlaidDroid** [comment]
Well...this works, but I don't know if it will make a difference if `let` is used instead of `const` (Obviously `const` cannot be used here, in the following code) :
```javascript
let newHost;

    if (app.config.hosts.length > 0) {
      const lastHost = app.config.hosts[app.config.hosts.length - 1];
      newHost = {
        ip: lastHost.ip,
        port: lastHost.port + 1,
        type: lastHost.type,
        oscString: "",
        udpString: "",
      };
    } else {
      newHost = {
        ip: "127.0.0.1",
        port: 8000,
        type: "osc",
        path: "/yo",
        oscString: "/yo 135 2.4 test",
      };
    }

    addHostLi(newHost);
    app.win.setContentSize(
      app.win.getContentSize()[0],
      addButton.getBoundingClientRect().bottom + 30
    );
  });
```

**Comment by MAKIO135** [comment]
Hey @PlaidDroid, catching up with the issue. Thanks for your solution. 
I might also consider preventing the user to delete the last host, what would you think about this solution ?

**Comment by PlaidDroid** [comment]
Yes yes that's perfect! That makes more sense.

**Comment by hugosaintemarie** [comment]
> I might also consider preventing the user to delete the last host, what would you think about this solution ?

My 2 cents @MAKIO135: UX-wise, I think we (almost) always should let users delete what they want to delete 🙂 I reckon it's ok to empty the interface, so as to populate it again. What do you think?

**Comment by MAKIO135** [comment]
@PlaidDroid: following @ashugeo's advice, I ended with your solution 🙏. 
Updated the OSX/Linux releases. 
Need to build Win release on my Win machine, coming soon.
